// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCharacter = "characters"

// Character mapped from table <characters>
type Character struct {
	ID      int32  `gorm:"column:id;primaryKey" json:"id"`
	Name    string `gorm:"column:name;not null" json:"name"`
	Rarity  int32  `gorm:"column:rarity;not null" json:"rarity"`
	Element int32  `gorm:"column:element;not null" json:"element"`
	Path    int32  `gorm:"column:path;not null" json:"path"`
	Picture []byte `gorm:"column:picture;not null" json:"picture"`
}

// TableName Character's table name
func (*Character) TableName() string {
	return TableNameCharacter
}
