// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameElement = "elements"

// Element mapped from table <elements>
type Element struct {
	ID      int32  `gorm:"column:id;primaryKey" json:"id"`
	Name    string `gorm:"column:name;not null" json:"name"`
	Enname  string `gorm:"column:enname;not null" json:"enname"`
	Picture []byte `gorm:"column:picture;not null" json:"picture"`
}

// TableName Element's table name
func (*Element) TableName() string {
	return TableNameElement
}
