// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePath = "paths"

// Path mapped from table <paths>
type Path struct {
	ID      int32  `gorm:"column:id;primaryKey" json:"id"`
	Name    string `gorm:"column:name;not null" json:"name"`
	Picture []byte `gorm:"column:picture;not null" json:"picture"`
}

// TableName Path's table name
func (*Path) TableName() string {
	return TableNamePath
}
