// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID                     int32     `gorm:"column:id;primaryKey" json:"id"`
	Username               string    `gorm:"column:username;not null" json:"username"`
	Password               string    `gorm:"column:password;not null" json:"password"`
	Email                  string    `gorm:"column:email;not null" json:"email"`
	Refreshtoken           string    `gorm:"column:refreshtoken" json:"refreshtoken"`
	Refreshtokenexpiredate *time.Time `gorm:"column:refreshtokenexpiredate" json:"refreshtokenexpiredate"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
